total_steps: 150000
batch_size: 1024
gradient_accum: 11
every_n_steps: 10
every_n_image: 5000
every_n_checkpoint: 1000
every_n_ema: 100
ema_decay: 0.99
ema_init: 0.01
ema_warmup: 3000

checkpoint_dir: "checkpoints"
checkpoint_init_dir: "0new_model"
seed: 42
lr: 1e-4
max_grad: 1.0
cfg_p: 0.1
warmup_steps: 2000
weight_decay: 0.03
latent_mean: 0.177456

is_restore: False