total_steps: 300000
batch_size: 1024
every_n_steps: 10
every_n_image: 1000
every_n_checkpoint: 1000
every_n_ema: 100
ema_decay: 0.99
checkpoint_dir: "checkpoints"
seed: 42
lr: 1e-4
max_grad: 1.0
cfg_p: 0.1
warmup_steps: 2000
weight_decay: 0.03
scaling_factor: 2.749165460782045